environment:
  matrix:
    - PY: "3.6"
      CONDA: "C:\\Miniconda3-x64"
      DOIT: "doit"
    - PY: "2.7"
      CONDA: "C:\\Miniconda-x64"
      DOIT: "doit==0.29.0"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  # parambokeh currently requires conda-forge?
  - conda config --add channels conda-forge
  - pip install %DOIT% https://github.com/ioam/ioamdoit/archive/deps_from_conda_recipe.zip
  - doit conda_recipe=conda.recipe/meta.yaml create_env
  - activate test-environment
  - doit install_pip_dependencies
  - doit capture_conda_env
  - doit develop_install

build: off

test_script:
  - doit all_tests
