language: generic

os:
  - linux

sudo: false

env:
  global:
    secure: qDzvmjcR6eLAmHx0ziN3Y5M8h65+OM+eBNERQsC3WSkeaD45rEE6a8w59dBdUzZBTLKO2RP8pKlgzxBZGOBlnLbTyN4RD/q2dA+gm5c0SDWWT4kVCiogJVsrzyRHVgMDmqDu56HPbQzhsW+5Qh2JKjVkkI7GwvGZRFB9WKQC8yjW/RfLvQ7bzX6jXbaHDYg9dywjI5u7da7HZKXyt/6nhebdaI19RdQHuESUqTADFEgdCKdzrNC+NqbJ8SUnNBBmkb1ZqoQ3/p1/Z/+uDi/2ThozE7Lz6gl8HtxVRnBiwNCDvZRE8uTB79+FlW0FJCVZ7qGO8jVWlVqy+WEEFh/6s9RP2PLd73CmItfF7BzSdxdurOYfnizboqCideSasDQK7XdeDiX4fPrgqbeesn8+XJ9vhxRAmpsNdZIU+2pivgviJwUZUwKwgzt3hf23ld9GpJg60wCfQRT8hiZc3/XsUPrzDjci7hwrRESqobPcuWk6xsFPTvJsTeOSLejP1wDOGAhufLTQIys26BSwHiaj6aI4RPK3Y4sy644m4IOfVvi3d+YfyN2Q5NO7QIwk5PjQBUEdwcIi3lAk2eAIjJamlDYFCRrnwuEoFinuFlUjtqpkuVTLgonTbk9KkIYnXeP3wYERrt4uOJtxDRCojBC0FI5rDbkhC3wP8Wef4EToQ+s=

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request  

jobs:
  include:
    - &tests
      stage: test
      env: PYTHON_VERSION="2.7"
      install:
      - source ./etc/travis-miniconda.sh
      - conda create -n test-environment python=$PYTHON_VERSION
      - source activate test-environment
      - conda install param
      - conda install -c bokeh "bokeh==0.12.9"
      # dependencies for testing
      - conda install -c conda-forge "holoviews>=1.8.4"
      - conda install pandas notebook flake8 pyparsing
      - python setup.py develop --no-deps
      - conda env export
      - conda list
      script:
        - flake8 --ignore E,W parambokeh
        - python doc/test_notebooks.py lint
        - python doc/test_notebooks.py

    - <<: *tests
      stage: test
      env: PYTHON_VERSION="3.6"

    - stage: deploy
      env: PYTHON_VERSION="3.6"
      install:
      - source ./etc/travis-miniconda.sh
      # for building and uploading packages
      - conda install conda-build=3.0.25
      - conda install anaconda-client
      script:
      - conda build conda.recipe
      - anaconda -t $CONDA_UPLOAD_TOKEN upload --force -u cball $HOME/miniconda/conda-bld/noarch/parambokeh*.tar.bz2
