git:
  depth: 100

language: generic

os:
  - linux

sudo: false

env:
  global:
    secure: qDzvmjcR6eLAmHx0ziN3Y5M8h65+OM+eBNERQsC3WSkeaD45rEE6a8w59dBdUzZBTLKO2RP8pKlgzxBZGOBlnLbTyN4RD/q2dA+gm5c0SDWWT4kVCiogJVsrzyRHVgMDmqDu56HPbQzhsW+5Qh2JKjVkkI7GwvGZRFB9WKQC8yjW/RfLvQ7bzX6jXbaHDYg9dywjI5u7da7HZKXyt/6nhebdaI19RdQHuESUqTADFEgdCKdzrNC+NqbJ8SUnNBBmkb1ZqoQ3/p1/Z/+uDi/2ThozE7Lz6gl8HtxVRnBiwNCDvZRE8uTB79+FlW0FJCVZ7qGO8jVWlVqy+WEEFh/6s9RP2PLd73CmItfF7BzSdxdurOYfnizboqCideSasDQK7XdeDiX4fPrgqbeesn8+XJ9vhxRAmpsNdZIU+2pivgviJwUZUwKwgzt3hf23ld9GpJg60wCfQRT8hiZc3/XsUPrzDjci7hwrRESqobPcuWk6xsFPTvJsTeOSLejP1wDOGAhufLTQIys26BSwHiaj6aI4RPK3Y4sy644m4IOfVvi3d+YfyN2Q5NO7QIwk5PjQBUEdwcIi3lAk2eAIjJamlDYFCRrnwuEoFinuFlUjtqpkuVTLgonTbk9KkIYnXeP3wYERrt4uOJtxDRCojBC0FI5rDbkhC3wP8Wef4EToQ+s=

stages:
  - test
  - doc
  - name: anaconda_deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - &tests
      stage: test
      env: PYTHON_VERSION="2.7"
      install:
      - source ./etc/travis-miniconda.sh
      - conda create -n test-environment python=$PYTHON_VERSION
      - source activate test-environment
      - conda install param
      - conda install -c bokeh "bokeh>=0.12.10"
      # dependencies for testing
      - pip install pytest pytest-nbsmoke
      - conda install -c ioam "holoviews>=1.9.0"
      - conda install pandas notebook flake8 pyparsing
      - python setup.py develop --no-deps
      - conda env export
      - conda list
      script:
        - flake8 --ignore E,W parambokeh
        - pytest --nbsmoke-lint examples/
        - pytest --nbsmoke-run examples/

    - <<: *tests
      env: PYTHON_VERSION="3.6"

    - stage: doc
      env: PYTHON_VERSION="3.6"
      install:
      # TODO: could (build and) use conda package; to be cleaned up
      # once auto versioning/package building is finalized
      - source ./etc/travis-miniconda.sh
      - conda create -n test-environment python=$PYTHON_VERSION
      - source activate test-environment
      - conda install param
      - conda install pandas
      - conda install -c bokeh "bokeh>=0.12.10"
      - conda install -c ioam "holoviews>=1.9.0"
      - conda install -c conda-forge notebook ipython sphinx beautifulsoup4 graphviz selenium phantomjs
      - pip install nbsite sphinx_ioam_theme
      - pip install -e .
      script:
      - cd doc
      - nbsite_nbpagebuild.py ioam parambokeh ../examples .
      - sphinx-build -b html . ./_build/html
      - nbsite_fix_links.py _build/html
      - touch ./_build/html/.nojekyll
      - nbsite_cleandisthtml.py ./_build/html take_a_chance
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./_build/html
          on:
            # TODO: depending on what we do for auto versioning/packaging,
            # should make this deploy somewhere for PRs etc, and only to the
            # main site on specific tag format.
            tags: true
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./_build/html
          repo: ioam-docs/parambokeh-master

    - stage: anaconda_deploy
      env: PYTHON_VERSION="3.6"
      install:
      - source ./etc/travis-miniconda.sh
      # for building and uploading packages
      - conda install conda-build=3.0.25
      - conda install anaconda-client
      script:
      - conda build conda.recipe
      - anaconda -t $CONDA_UPLOAD_TOKEN upload --force -u cball $HOME/miniconda/conda-bld/noarch/parambokeh*.tar.bz2
