package:
  name: parambokeh
  version: {{ environ['GIT_DESCRIBE_TAG'].lstrip('v') }}.{{ GIT_BUILD_STR }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python
    - param
    - bokeh >=0.12.9,<0.12.10

test:
  imports:
    - parambokeh

about:
  home: https://github.com/ioam/parambokeh
  summary: ParamBokeh provides an easy way to generate a UI for param based classes in the notebook or on bokeh server.
  license: BSD 3-Clause
