{% set sdata = load_setup_py_data() %}

package:
  name: parambokeh
  # TODO: see autover
  version: {{ os.environ.get("VERSIONHACK") }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata.get('install_requires',{}) %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    {% for dep in sdata.get('tests_require',{}) %}
    - {{ dep }}
    {% endfor %}
  imports:
    - parambokeh

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
